apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: litmus

commonAnnotations:
  linkerd.io/inject: enabled

resources:
  - namespace.yaml

helmCharts:
  - name: litmus
    repo: https://litmuschaos.github.io/litmus-helm/
    version: 2.7.3
    releaseName: litmus
    namespace: litmus
    valuesFile: values.yaml

patchesStrategicMerge:
  - overlays/ingress.yaml

namespace: litmus