apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: metallb

resources:
  - github.com/metallb/metallb//manifests?ref=v0.12.1
  - configmap.yaml

namespace: metallb-system