apiVersion: v1
kind: Secret
metadata:
  name: litmuschaos-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: litmuschaos
  url: https://litmuschaos.github.io/litmus-helm/
  type: helm