apiVersion: v1
kind: Secret
metadata:
  name: loki-stack-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: loki-stack
  url: https://grafana.github.io/helm-charts/
  type: helm
