apiVersion: v1
kind: Secret
metadata:
  name: rancher-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  name: rancher-latest
  url: https://releases.rancher.com/server-charts/latest
  type: helm