apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: cert-manager

resources:
  - namespace.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.7.1
    releaseName: cert-manager
    namespace: cert-manager

namespace: cert-manager