apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  tier: security
  app: gatekeeper

bases:
  - ../../base

  # patched downstream for github.com/krackjack29/gatekeeper-ui/deploy
  - github.com/kevinobee/gatekeeper-ui/deploy

resources:
  - ingress.yaml