apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: gatekeeper

resources:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.7/deploy/gatekeeper.yaml

  # OPA Gatekeeper Library
  - github.com/open-policy-agent/gatekeeper-library/library/general

  - constraints.yaml

patches:
  - path: patches/gatekeeper-audit.jsonpatch.yaml
    target:
      name: gatekeeper-audit
      kind: Deployment
      group: apps
      version: v1
  - path: patches/gatekeeper-controller-manager.jsonpatch.yaml
    target:
      name: gatekeeper-controller-manager
      kind: Deployment
      group: apps
      version: v1
  - path: patches/gatekeeper-policy-manager.jsonpatch.yaml
    target:
      name: gatekeeper-policy-manager
      kind: Deployment
      group: apps
      version: v1

