#
#  Author: Hari Sekhon
#  Date: 2021-11-23 11:42:08 +0000 (Tue, 23 Nov 2021)
#
#  vim:ts=2:sts=2:sw=2:et
#
#  https://github.com/HariSekhon/Kubernetes-configs
#
#  License: see accompanying Hari Sekhon LICENSE file
#
#  If you're using my code you're welcome to connect with me on LinkedIn and optionally send me feedback to help steer this or other code I publish
#
#  https://www.linkedin.com/in/HariSekhon
#

# ============================================================================ #
#A r g o C D   A p p l i c a t i o n   C o n t r o l l e r   R e s o u r c e s   P a t c h
# ============================================================================ #

# run: kubectl patch sts argocd-application-controller -n argocd --type json --patch "$(cat argocd-resources.argocd-application-controller.jsonpatch.yaml)"

---
- op: add
  path: /spec/template/spec/containers/0/resources
  value:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 1.2
      memory: 2.7Gi
