apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: ingress-nginx

commonAnnotations:
  linkerd.io/inject: enabled

resources:
  - namespace.yaml

helmCharts:
  - name: ingress-nginx
    repo: https://kubernetes.github.io/ingress-nginx
    version: 4.0.18
    releaseName: ingress-nginx
    namespace: ingress-nginx
    valuesFile: values.yaml

namespace: ingress-nginx

patchesStrategicMerge:
  - CVE-2021-25742-configmap.yaml
