apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: argocd

namespace: argocd

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.2.5/manifests/install.yaml


# ArgoCD doesn't come with default resources - https://github.com/argoproj/argo-cd/issues/7772
# origin: https://github.dev/HariSekhon/Kubernetes-configs/blob/f3fe17c2ffd4524237b1439bcc0aebdeff46a0eb/argocd-kustomization.yaml#L84-L126
patches:
  - path: patches/argocd-resources.argocd-application-controller.jsonpatch.yaml
    target:
      name: argocd-application-controller
      kind: StatefulSet
      group: apps
      version: v1
  - path: patches/argocd-resources.argocd-dex-server.jsonpatch.yaml
    target:
      name: argocd-dex-server
      kind: Deployment
      group: apps
      version: v1
  - path: patches/argocd-resources.argocd-redis.jsonpatch.yaml
    target:
      name: argocd-redis
      kind: Deployment
      group: apps
      version: v1
  - path: patches/argocd-resources.argocd-repo-server.jsonpatch.yaml
    target:
      name: argocd-repo-server
      kind: Deployment
      group: apps
      version: v1
  - path: patches/argocd-resources.argocd-server.jsonpatch.yaml
    target:
      name: argocd-server
      kind: Deployment
      group: apps
      version: v1
