apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: starboard

commonAnnotations:
  linkerd.io/inject: enabled

resources:
  - namespace.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/ciskubebenchreports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/clustercompliancedetailreports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/clustercompliancereports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/clusterconfigauditreports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/clustervulnerabilityreports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/configauditreports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/kubehunterreports.crd.yaml
  - https://raw.githubusercontent.com/aquasecurity/starboard/main/deploy/crd/vulnerabilityreports.crd.yaml

helmCharts:
  - name: starboard-operator
    repo: https://aquasecurity.github.io/helm-charts/
    version: 0.9.1
    releaseName: starboard-operator
    namespace: starboard-system
    valuesFile: values.yaml

  - name: starboard-exporter
    repo: https://giantswarm.github.io/giantswarm-catalog
    version: 0.3.0
    releaseName: starboard-exporter
    namespace: starboard-system

namespace: starboard-system