apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: argo

commonAnnotations:
  linkerd.io/inject: enabled

resources:
- namespace.yaml

helmCharts:
  - name: argo-events
    repo: https://argoproj.github.io/argo-helm
    version: 1.12.0
    releaseName: argo-events
    namespace: argo-events

namespace: argo-events