apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: gatekeeper-policy-manager

commonAnnotations:
  linkerd.io/inject: enabled

bases:
  - github.com/sighupio/gatekeeper-policy-manager?ref=v0.5.1

namespace: gatekeeper-system

resources:
  - ingress.yaml
