apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-slim
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kevinobee/k8s-gitops.git'
    targetRevision: main
    path: gitops/slim
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true