apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: gatekeeper

commonAnnotations:
  linkerd.io/inject: enabled

bases:
  - https://raw.githubusercontent.com/open-policy-agent/gatekeeper/release-3.7/deploy/gatekeeper.yaml
  - github.com/sighupio/gatekeeper-policy-manager?ref=v0.5.1

resources:
  - ingress.yaml

namespace: gatekeeper-system