apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventsource-controller
spec:
  template:
    spec:
      containers:
      - name: eventsource-controller
        resources:
          limits:
            cpu: 10m
            memory: 32Mi
          requests:
            cpu: 10m
            memory: 32Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: eventbus-controller
spec:
  template:
    spec:
      containers:
      - name: eventbus-controller
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: sensor-controller
spec:
  template:
    spec:
      containers:
      - name: sensor-controller
        resources:
          limits:
            cpu: 50m
            memory: 64Mi
          requests:
            cpu: 10m
            memory: 32Mi
