apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: linkerd

commonAnnotations:
  linkerd.io/inject: enabled

resources:
- namespace.yaml
- install.yaml

namespace: linkerd-viz