apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gatekeeper-library
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/kevinobee/k8s-gitops.git'
    targetRevision: HEAD
    path: apps/gatekeeper-library
  destination:
    server: https://kubernetes.default.svc
    namespace: gatekeeper-system
  syncPolicy:
    automated: {}
