apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://dl.gitea.io/charts/'
    targetRevision: 4.1.1
    chart: gitea
    helm:
      parameters:
        - name: gitea.admin.username
          value: 'gitea'
        - name: gitea.admin.password
          value: 'ChangeMe'
        - name: ingress.enabled
          value: 'true'
        - name: ingress.className
          value: 'nginx'
        - name: ingress.hosts[0].host
          value: 'git.local'
        - name: ingress.hosts[0].paths[0].path
          value: '/'
        - name: ingress.hosts[0].paths[0].pathType
          value: 'Prefix'
        - name: gitea.startupProbe.enabled
          value: 'true'
        - name: gitea.metrics.enabled
          value: 'true'
  destination:
    namespace: gitea
    server: 'https://kubernetes.default.svc'
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
