apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: gatekeeper-library

commonAnnotations:
  linkerd.io/inject: enabled

# Issue: using app-of-apps pattern and orchestrating synchronization using sync waves
# ref: https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.7-1.8/#health-assessment-of-argoprojioapplication-crd-has-been-removed
resources:
  - github.com/open-policy-agent/gatekeeper-library/library/general