name: K8S Policy Check

on:
  push:
    paths:
      - 'apps/**'
      - 'gitops/**'

  workflow_dispatch:

env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }}

jobs:

  scan:
    name: Datree Policy Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate kustomize YAML
        run: kubectl kustomize --enable-helm > kustomize.yaml

      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: kustomize.yaml
          cliArguments: '--schema-version 1.21.0 --ignore-missing-schemas --policy Dev'

      - name: Upload Kustomize YAML
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: kustomize
          path: kustomize.yaml
