apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: argocd

commonAnnotations:
  linkerd.io/inject: enabled

bases:
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.1/manifests/install.yaml

resources:
  - namespace.yaml

patchesStrategicMerge:
  - overlays/argo-cd-cm.yaml

namespace: argocd
