apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  k8s-app: argocd

commonAnnotations:
  linkerd.io/inject: enabled

bases:
  # Non-HA
  - https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/install.yaml
  # HA
  # https://raw.githubusercontent.com/argoproj/argo-cd/v2.3.3/manifests/ha/install.yaml

resources:
  - namespace.yaml

patchesStrategicMerge:
  - overlays/argo-cd-cm.yaml
  - overlays/resource-limits.yaml

namespace: argocd
